### PR TITLE
Fix style

### PR DESCRIPTION
**Pull request by ikmckenz**
This is a very large pull request, but it doesn't actually change any functionality. It simply brings the style of the code to a semi-uniform and almost-pep8 compliant state. 

Before this pull request the code base gets a score of -1.07/10 from pylint, and after we get up to 5.90/10. 

The major things changed are white space (only spaces, instead of the potentially dangerous mix of tabs and spaces that was used before), and now there are no semicolons after statements. I don't have hardware to test against (yet) but it would be good to test this before merging to ensure that the functionality that was working is still working, and the functionality that was broken is still broken.

### CODE REVIEW

**Comment by ikmckenz** [comment]
Looks like codecov is upset that the coverage isn't increasing and thus giving me the red X. I'll make it my next project to add more tests.

**Comment by ikmckenz** [comment]
Now that Cyton testing is merged in, I'll fix the merge conflicts with this branch later today.

**Comment by ikmckenz** [comment]
This should be ready to merge if everyone else is happy with it. I am happy to answer any questions to help with reviewing this change.

**Comment by ikmckenz** [comment]
Hey @andrewjaykeller , what are your thoughts on this pull request? Love it? Hate it?

**Comment by andrewjaykeller** [comment]
I love the idea, where you able to test it?

**Comment by ikmckenz** [comment]
> I love the idea, where you able to test it?

Yep! I actually made this branch before adding all the new testing to the Cyton code, and this new testing confirmed that no functionality is changed by accident, and all of the changes are stylistic.

**Comment by ikmckenz** [comment]
I added some more changes that I originally was saving for another pull request. This includes enforcing print functions (rather than statements) using `from __future__ import print_function` and changing the existing print statements around. This resolves #56. 

The pylint score is now up to 6.88/10 on this branch.

**Comment by daniellasry** [comment]
hey @ikmckenz , is this still ready to merge?
I tested it locally with a cyton board and it seems to work. The codecov still looks upset, but i'm not entirely sure what it's upset about.

Thanks!

**Comment by ikmckenz** [comment]
Hey @daniellasry , I fixed the merge conflicts and it is ready to merge again. Codecov is happy now :) . Codecov originally was upset because the diff coverage was less than the overall coverage, it looks like that check (patch coverage) was removed. Even if that check was still there, I think this is still okay to merge because:
1. This only changes code style, not functionality.
2. I actually wrote the Cyton testing code (#100) to ensure that 1 was true, and the tests show no changes between master and this branch.

**Pull request merged**
