### PR TITLE
Fix Issue with plugin_interface.py imports

### PR DESCRIPTION
**Pull request by tushar-c**
`plugin_interface.py` : when imported in other files as 'import plugin_interface as plugintypes', this causes missing modules errors. The commit would have the aforementioned file manually put in the `plugins` directory and the imports changed to : `from . import plugin_interface as plugintypes`

### CODE REVIEW

**Comment by zekailin00** [comment]
I think I figure our what the cause is.
The problem is after you install OpenBCI `sudo python3 setup.py install`, the `plugin_interface.py` is in the `OpenBCI_Python-1.0.2-py3.5.egg/openbci/plugins` folder. Moving `plugin_interface.py` to the `OpenBCI_Python-1.0.2-py3.5.egg` folder can temporarily solve this problem. 

The `user.py` works well at any time without this bug, because `import openbci.cyton as bci` imports the openbci directly in the folder we cloned, not from python packages we installed, and `plugin_interface.py` this cloned folder as well. 

This bug only occurs if we run the python programs that do not stay together with openbci folder and plugin_interface.py. For example, test_wifi.py or test_cyton.py are in the folder called tests. In those cases, when we `import openbci`, this will be import from python packages instead of from the openbci folder we cloned from Github. 

To solve this problem, the installation part has be fix. So `plugin_interface.py` has to be in the `OpenBCI_Python-1.0.2-py3.5.egg` folder.

**Comment by tushar-c** [comment]
> I think I figure our what the cause is.
> The problem is after you install OpenBCI `sudo python3 setup.py install`, the `plugin_interface.py` is in the `OpenBCI_Python-1.0.2-py3.5.egg/openbci/plugins` folder. Moving `plugin_interface.py` to the `OpenBCI_Python-1.0.2-py3.5.egg` folder can temporarily solve this problem.
> 
> The `user.py` works well at any time without this bug, because `import openbci.cyton as bci` imports the openbci directly in the folder we cloned, not from python packages we installed, and `plugin_interface.py` this cloned folder as well.
> 
> This bug only occurs if we run the python programs that do not stay together with openbci folder and plugin_interface.py. For example, test_wifi.py or test_cyton.py are in the folder called tests. In those cases, when we `import openbci`, this will be import from python packages instead of from the openbci folder we cloned from Github.
> 
> To solve this problem, the installation part has be fix. So `plugin_interface.py` has to be in the `OpenBCI_Python-1.0.2-py3.5.egg` folder.

And so I did make a 'temporary' fix to that you could install from here: https://github.com/tushar-c/openbci-fixed .

**Comment by daniellasry** [comment]
I believe you are having this issue because you need to run:
```
python setup.py develop
```
Then you will be able to run: 
```
python tests/test_cyton.py
```
From [this post](https://stackoverflow.com/questions/19048732/python-setup-py-develop-vs-install):
> That way you can edit the source code and see the changes directly without having to reinstall every time that you make a little change. This is useful when you are the developer of that project hence the name develop. If you are just installing someone else's package you should use install


Closing this pull request, since it is old and the code seems to have been merged. If you are still having trouble, please open a new issue!

**Comment by rivasd** [comment]
the issue that was supposed to be fixed by this PR, namely #91 , is still present in the 1.0.2 release. Im not really sure why either because it would be easily fixed by moving the file named `plugin_interface.py` that is in the project root to the `openbci/plugins` directory and doing a search-replace for all instances of `import plugin_interface as` to `import .plugin_interface as` (adding the dot for relative import). If you need assistance for the Pypi updating process or anything else feel free to ping me on the neurotechx slack @ drivas.

**Pull request closed without merging**
